version: '3.4'

services:
  whoami:
    image: ruanbekker/whoami:me
    networks:
      - public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=public"
        - "traefik.backend=whoami"
        - "traefik.port=8000"
        - "traefik.frontend.rule=Host:whoami.${DOMAIN}"
        - "traefik.frontend.headers.SSLRedirect=true"
        - "traefik.frontend.entryPoints=http,https"

networks:
  public:
    external: true
